//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Megalaba3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activities
    {
        public System.Guid ID { get; set; }
        public System.Guid DisciplineID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<System.Guid> StudentID { get; set; }
        public Nullable<int> Cost { get; set; }
        public bool Done { get; set; }
    
        public virtual Discipline Discipline { get; set; }
        public virtual Users Users { get; set; }
    }
}
