//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Megalaba3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requests
    {
        public System.Guid ID { get; set; }
        public System.Guid DisciplineID { get; set; }
        public System.Guid UserID { get; set; }
        public System.Guid ActivityID { get; set; }
    
        public virtual Activities Activities { get; set; }
        public virtual Discipline Discipline { get; set; }
        public virtual Users Users { get; set; }
    }
}
